// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsPlus.Data;

namespace SportsPlus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201005023130_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsPlus.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Vancouver",
                            Population = 1000000,
                            Province = "British Columbia"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Surrey",
                            Population = 500000,
                            Province = "British Columbia"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Calgary",
                            Population = 850000,
                            Province = "Alberta"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Ottawa",
                            Population = 2000000,
                            Province = "Ontario"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Saskatoon",
                            Population = 253000,
                            Province = "Sasktchewan"
                        });
                });

            modelBuilder.Entity("SportsPlus.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName1")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamName1");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Sven",
                            LastName = "Baertschi",
                            Position = "Forward",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Hendrik",
                            LastName = "Sedin",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 3,
                            FirstName = "John",
                            LastName = "Rooster",
                            Position = "Right Wing",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 4,
                            FirstName = "Bob",
                            LastName = "Plumber",
                            Position = "Defense",
                            TeamName = "Oilers"
                        });
                });

            modelBuilder.Entity("SportsPlus.Models.Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceCode = "BC",
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceCode = "ON",
                            ProvinceName = "Ontario"
                        },
                        new
                        {
                            ProvinceCode = "SK",
                            ProvinceName = "Saskatchewan"
                        },
                        new
                        {
                            ProvinceCode = "AB",
                            ProvinceName = "Alberta"
                        });
                });

            modelBuilder.Entity("SportsPlus.Models.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamName");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamName = "Canucks",
                            City = "Vancouver",
                            Country = "Canada"
                        },
                        new
                        {
                            TeamName = "Oilers",
                            City = "Edmonton",
                            Country = "Canada"
                        },
                        new
                        {
                            TeamName = "Flames",
                            City = "Calgary",
                            Country = "Canada"
                        },
                        new
                        {
                            TeamName = "Leafs",
                            City = "Toronto",
                            Country = "Canada"
                        });
                });

            modelBuilder.Entity("SportsPlus.Models.City", b =>
                {
                    b.HasOne("SportsPlus.Models.Province", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode");
                });

            modelBuilder.Entity("SportsPlus.Models.Player", b =>
                {
                    b.HasOne("SportsPlus.Models.Team", "Team")
                        .WithMany("Platers")
                        .HasForeignKey("TeamName1");
                });
#pragma warning restore 612, 618
        }
    }
}
